name = "CrudePythonTranslator"
uuid = "58c7ca78-788c-4120-b21e-78fc10394fb4"
authors = ["Gunnar Farnebäck <gunnar.farneback@contextvision.se>"]
version = "1.0.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Multibreak = "2db7fbaf-c681-4fb2-9fc5-9b884bdd742d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Multibreak = "0.2"
PyCall = "1.95"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
